name: C++ Radix Sort Testing

on: [push]

jobs:
  setup-and-compile:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Install C++ Compiler
      run: sudo apt-get update && sudo apt-get install -y g++
    - name: Compile the Project
      run: g++ -o sort_program dn1.cpp 2> napaka.txt || echo "Compilation Error" > napaka.txt
    - name: Upload Compilation Error if Exists
      uses: actions/upload-artifact@v2
      with:
        name: compilation_errors
        path: napaka.txt

  test:
    needs: setup-and-compile
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: compilation_errors
    - name: Check for Compilation Errors
      run: |
        if [ -s napaka.txt ]; then
          cat napaka.txt
          exit 1
        fi
    - name: Run Test Cases
      run: |
        echo -e "3\n2\n1" > test_input.txt
        ./sort_program test_input.txt
        sort -n test_input.txt > expected_output.txt
        if cmp -s expected_output.txt out.txt; then
          echo "Tesst Passed"
        else
          echo "Test Failed: Output does not match expected output"
          exit 1
        fi
